env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 13
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
  - prettier
rules: {}
